//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.19 at 12:07:06 PM BST 
//


package uk.ac.ucl.chem.ccs.ramp.rfq;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.ucl.chem.ccs.ramp.rfq package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.ucl.chem.ccs.ramp.rfq
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestForQuotation }
     * 
     */
    public RequestForQuotation createRequestForQuotation() {
        return new RequestForQuotation();
    }

    /**
     * Create an instance of {@link RequestForQuotation.Request }
     * 
     */
    public RequestForQuotation.Request createRequestForQuotationRequest() {
        return new RequestForQuotation.Request();
    }

    /**
     * Create an instance of {@link RequestForQuotation.Request.Cores }
     * 
     */
    public RequestForQuotation.Request.Cores createRequestForQuotationRequestCores() {
        return new RequestForQuotation.Request.Cores();
    }

    /**
     * Create an instance of {@link RequestForQuotation.Request.Disk }
     * 
     */
    public RequestForQuotation.Request.Disk createRequestForQuotationRequestDisk() {
        return new RequestForQuotation.Request.Disk();
    }

    /**
     * Create an instance of {@link RequestForQuotation.Request.Cores.Nodes }
     * 
     */
    public RequestForQuotation.Request.Cores.Nodes createRequestForQuotationRequestCoresNodes() {
        return new RequestForQuotation.Request.Cores.Nodes();
    }

}
