//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.19 at 12:07:06 PM BST 
//


package uk.ac.ucl.chem.ccs.ramp.rfq;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Request">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CPUHourCost" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="EndTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                   &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *                   &lt;element name="OperatingSystem" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Unknown"/>
 *                         &lt;enumeration value="MACOS"/>
 *                         &lt;enumeration value="ATTUNIX"/>
 *                         &lt;enumeration value="DGUX"/>
 *                         &lt;enumeration value="DECNT"/>
 *                         &lt;enumeration value="Tru64_UNIX"/>
 *                         &lt;enumeration value="OpenVMS"/>
 *                         &lt;enumeration value="HPUX"/>
 *                         &lt;enumeration value="AIX"/>
 *                         &lt;enumeration value="MVS"/>
 *                         &lt;enumeration value="OS400"/>
 *                         &lt;enumeration value="OS_2"/>
 *                         &lt;enumeration value="JavaVM"/>
 *                         &lt;enumeration value="MSDOS"/>
 *                         &lt;enumeration value="WIN3x"/>
 *                         &lt;enumeration value="WIN95"/>
 *                         &lt;enumeration value="WIN98"/>
 *                         &lt;enumeration value="WINNT"/>
 *                         &lt;enumeration value="WINCE"/>
 *                         &lt;enumeration value="NCR3000"/>
 *                         &lt;enumeration value="NetWare"/>
 *                         &lt;enumeration value="OSF"/>
 *                         &lt;enumeration value="DC_OS"/>
 *                         &lt;enumeration value="Reliant_UNIX"/>
 *                         &lt;enumeration value="SCO_UnixWare"/>
 *                         &lt;enumeration value="SCO_OpenServer"/>
 *                         &lt;enumeration value="Sequent"/>
 *                         &lt;enumeration value="IRIX"/>
 *                         &lt;enumeration value="Solaris"/>
 *                         &lt;enumeration value="SunOS"/>
 *                         &lt;enumeration value="U6000"/>
 *                         &lt;enumeration value="ASERIES"/>
 *                         &lt;enumeration value="TandemNSK"/>
 *                         &lt;enumeration value="TandemNT"/>
 *                         &lt;enumeration value="BS2000"/>
 *                         &lt;enumeration value="LINUX"/>
 *                         &lt;enumeration value="Lynx"/>
 *                         &lt;enumeration value="XENIX"/>
 *                         &lt;enumeration value="VM"/>
 *                         &lt;enumeration value="Interactive_UNIX"/>
 *                         &lt;enumeration value="BSDUNIX"/>
 *                         &lt;enumeration value="FreeBSD"/>
 *                         &lt;enumeration value="NetBSD"/>
 *                         &lt;enumeration value="GNU_Hurd"/>
 *                         &lt;enumeration value="OS9"/>
 *                         &lt;enumeration value="MACH_Kernel"/>
 *                         &lt;enumeration value="Inferno"/>
 *                         &lt;enumeration value="QNX"/>
 *                         &lt;enumeration value="EPOC"/>
 *                         &lt;enumeration value="IxWorks"/>
 *                         &lt;enumeration value="VxWorks"/>
 *                         &lt;enumeration value="MiNT"/>
 *                         &lt;enumeration value="BeOS"/>
 *                         &lt;enumeration value="HP_MPE"/>
 *                         &lt;enumeration value="NextStep"/>
 *                         &lt;enumeration value="PalmPilot"/>
 *                         &lt;enumeration value="Rhapsody"/>
 *                         &lt;enumeration value="Windows_2000"/>
 *                         &lt;enumeration value="Dedicated"/>
 *                         &lt;enumeration value="OS_390"/>
 *                         &lt;enumeration value="VSE"/>
 *                         &lt;enumeration value="TPF"/>
 *                         &lt;enumeration value="Windows_R_Me"/>
 *                         &lt;enumeration value="Caldera_Open_UNIX"/>
 *                         &lt;enumeration value="OpenBSD"/>
 *                         &lt;enumeration value="Not_Applicable"/>
 *                         &lt;enumeration value="Windows_XP"/>
 *                         &lt;enumeration value="z_OS"/>
 *                         &lt;enumeration value="other"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="OSVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Architecture" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="sparc"/>
 *                         &lt;enumeration value="powerpc"/>
 *                         &lt;enumeration value="x86"/>
 *                         &lt;enumeration value="x86_32"/>
 *                         &lt;enumeration value="x86_64"/>
 *                         &lt;enumeration value="parisc"/>
 *                         &lt;enumeration value="mips"/>
 *                         &lt;enumeration value="ia64"/>
 *                         &lt;enumeration value="arm"/>
 *                         &lt;enumeration value="other"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CPUSpeed" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="WallTime" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="InterNodeBandwidth" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="RAMPerCore" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="Disk" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="TotalDiskSpace" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="NodeDiskSpace" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Cores">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="TotalCores" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="Nodes">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="NodeCount" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                       &lt;element name="NodeCores" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "request"
})
@XmlRootElement(name = "RequestForQuotation")
public class RequestForQuotation {

    @XmlElement(name = "Request", required = true)
    protected RequestForQuotation.Request request;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link RequestForQuotation.Request }
     *     
     */
    public RequestForQuotation.Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestForQuotation.Request }
     *     
     */
    public void setRequest(RequestForQuotation.Request value) {
        this.request = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CPUHourCost" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="EndTime" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
     *         &lt;element name="OperatingSystem" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Unknown"/>
     *               &lt;enumeration value="MACOS"/>
     *               &lt;enumeration value="ATTUNIX"/>
     *               &lt;enumeration value="DGUX"/>
     *               &lt;enumeration value="DECNT"/>
     *               &lt;enumeration value="Tru64_UNIX"/>
     *               &lt;enumeration value="OpenVMS"/>
     *               &lt;enumeration value="HPUX"/>
     *               &lt;enumeration value="AIX"/>
     *               &lt;enumeration value="MVS"/>
     *               &lt;enumeration value="OS400"/>
     *               &lt;enumeration value="OS_2"/>
     *               &lt;enumeration value="JavaVM"/>
     *               &lt;enumeration value="MSDOS"/>
     *               &lt;enumeration value="WIN3x"/>
     *               &lt;enumeration value="WIN95"/>
     *               &lt;enumeration value="WIN98"/>
     *               &lt;enumeration value="WINNT"/>
     *               &lt;enumeration value="WINCE"/>
     *               &lt;enumeration value="NCR3000"/>
     *               &lt;enumeration value="NetWare"/>
     *               &lt;enumeration value="OSF"/>
     *               &lt;enumeration value="DC_OS"/>
     *               &lt;enumeration value="Reliant_UNIX"/>
     *               &lt;enumeration value="SCO_UnixWare"/>
     *               &lt;enumeration value="SCO_OpenServer"/>
     *               &lt;enumeration value="Sequent"/>
     *               &lt;enumeration value="IRIX"/>
     *               &lt;enumeration value="Solaris"/>
     *               &lt;enumeration value="SunOS"/>
     *               &lt;enumeration value="U6000"/>
     *               &lt;enumeration value="ASERIES"/>
     *               &lt;enumeration value="TandemNSK"/>
     *               &lt;enumeration value="TandemNT"/>
     *               &lt;enumeration value="BS2000"/>
     *               &lt;enumeration value="LINUX"/>
     *               &lt;enumeration value="Lynx"/>
     *               &lt;enumeration value="XENIX"/>
     *               &lt;enumeration value="VM"/>
     *               &lt;enumeration value="Interactive_UNIX"/>
     *               &lt;enumeration value="BSDUNIX"/>
     *               &lt;enumeration value="FreeBSD"/>
     *               &lt;enumeration value="NetBSD"/>
     *               &lt;enumeration value="GNU_Hurd"/>
     *               &lt;enumeration value="OS9"/>
     *               &lt;enumeration value="MACH_Kernel"/>
     *               &lt;enumeration value="Inferno"/>
     *               &lt;enumeration value="QNX"/>
     *               &lt;enumeration value="EPOC"/>
     *               &lt;enumeration value="IxWorks"/>
     *               &lt;enumeration value="VxWorks"/>
     *               &lt;enumeration value="MiNT"/>
     *               &lt;enumeration value="BeOS"/>
     *               &lt;enumeration value="HP_MPE"/>
     *               &lt;enumeration value="NextStep"/>
     *               &lt;enumeration value="PalmPilot"/>
     *               &lt;enumeration value="Rhapsody"/>
     *               &lt;enumeration value="Windows_2000"/>
     *               &lt;enumeration value="Dedicated"/>
     *               &lt;enumeration value="OS_390"/>
     *               &lt;enumeration value="VSE"/>
     *               &lt;enumeration value="TPF"/>
     *               &lt;enumeration value="Windows_R_Me"/>
     *               &lt;enumeration value="Caldera_Open_UNIX"/>
     *               &lt;enumeration value="OpenBSD"/>
     *               &lt;enumeration value="Not_Applicable"/>
     *               &lt;enumeration value="Windows_XP"/>
     *               &lt;enumeration value="z_OS"/>
     *               &lt;enumeration value="other"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="OSVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Architecture" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="sparc"/>
     *               &lt;enumeration value="powerpc"/>
     *               &lt;enumeration value="x86"/>
     *               &lt;enumeration value="x86_32"/>
     *               &lt;enumeration value="x86_64"/>
     *               &lt;enumeration value="parisc"/>
     *               &lt;enumeration value="mips"/>
     *               &lt;enumeration value="ia64"/>
     *               &lt;enumeration value="arm"/>
     *               &lt;enumeration value="other"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CPUSpeed" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="WallTime" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="InterNodeBandwidth" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="RAMPerCore" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="Disk" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="TotalDiskSpace" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="NodeDiskSpace" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Cores">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="TotalCores" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="Nodes">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="NodeCount" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                             &lt;element name="NodeCores" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cpuHourCost",
        "endDate",
        "endTime",
        "startDate",
        "startTime",
        "operatingSystem",
        "osVersion",
        "architecture",
        "cpuSpeed",
        "wallTime",
        "interNodeBandwidth",
        "ramPerCore",
        "disk",
        "cores"
    })
    public static class Request {

        @XmlElement(name = "CPUHourCost", required = true)
        protected BigInteger cpuHourCost;
        @XmlElement(name = "EndDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar endDate;
        @XmlElement(name = "EndTime", required = true)
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar endTime;
        @XmlElement(name = "StartDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar startDate;
        @XmlElement(name = "StartTime")
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar startTime;
        @XmlElement(name = "OperatingSystem")
        protected String operatingSystem;
        @XmlElement(name = "OSVersion")
        protected String osVersion;
        @XmlElement(name = "Architecture")
        protected String architecture;
        @XmlElement(name = "CPUSpeed")
        protected BigInteger cpuSpeed;
        @XmlElement(name = "WallTime")
        protected BigInteger wallTime;
        @XmlElement(name = "InterNodeBandwidth")
        protected BigInteger interNodeBandwidth;
        @XmlElement(name = "RAMPerCore")
        protected BigInteger ramPerCore;
        @XmlElement(name = "Disk")
        protected RequestForQuotation.Request.Disk disk;
        @XmlElement(name = "Cores", required = true)
        protected RequestForQuotation.Request.Cores cores;

        /**
         * Gets the value of the cpuHourCost property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCPUHourCost() {
            return cpuHourCost;
        }

        /**
         * Sets the value of the cpuHourCost property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCPUHourCost(BigInteger value) {
            this.cpuHourCost = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndDate(XMLGregorianCalendar value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the endTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndTime() {
            return endTime;
        }

        /**
         * Sets the value of the endTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndTime(XMLGregorianCalendar value) {
            this.endTime = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartDate(XMLGregorianCalendar value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the startTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartTime() {
            return startTime;
        }

        /**
         * Sets the value of the startTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartTime(XMLGregorianCalendar value) {
            this.startTime = value;
        }

        /**
         * Gets the value of the operatingSystem property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOperatingSystem() {
            return operatingSystem;
        }

        /**
         * Sets the value of the operatingSystem property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOperatingSystem(String value) {
            this.operatingSystem = value;
        }

        /**
         * Gets the value of the osVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOSVersion() {
            return osVersion;
        }

        /**
         * Sets the value of the osVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOSVersion(String value) {
            this.osVersion = value;
        }

        /**
         * Gets the value of the architecture property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArchitecture() {
            return architecture;
        }

        /**
         * Sets the value of the architecture property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArchitecture(String value) {
            this.architecture = value;
        }

        /**
         * Gets the value of the cpuSpeed property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCPUSpeed() {
            return cpuSpeed;
        }

        /**
         * Sets the value of the cpuSpeed property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCPUSpeed(BigInteger value) {
            this.cpuSpeed = value;
        }

        /**
         * Gets the value of the wallTime property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getWallTime() {
            return wallTime;
        }

        /**
         * Sets the value of the wallTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setWallTime(BigInteger value) {
            this.wallTime = value;
        }

        /**
         * Gets the value of the interNodeBandwidth property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getInterNodeBandwidth() {
            return interNodeBandwidth;
        }

        /**
         * Sets the value of the interNodeBandwidth property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setInterNodeBandwidth(BigInteger value) {
            this.interNodeBandwidth = value;
        }

        /**
         * Gets the value of the ramPerCore property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getRAMPerCore() {
            return ramPerCore;
        }

        /**
         * Sets the value of the ramPerCore property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRAMPerCore(BigInteger value) {
            this.ramPerCore = value;
        }

        /**
         * Gets the value of the disk property.
         * 
         * @return
         *     possible object is
         *     {@link RequestForQuotation.Request.Disk }
         *     
         */
        public RequestForQuotation.Request.Disk getDisk() {
            return disk;
        }

        /**
         * Sets the value of the disk property.
         * 
         * @param value
         *     allowed object is
         *     {@link RequestForQuotation.Request.Disk }
         *     
         */
        public void setDisk(RequestForQuotation.Request.Disk value) {
            this.disk = value;
        }

        /**
         * Gets the value of the cores property.
         * 
         * @return
         *     possible object is
         *     {@link RequestForQuotation.Request.Cores }
         *     
         */
        public RequestForQuotation.Request.Cores getCores() {
            return cores;
        }

        /**
         * Sets the value of the cores property.
         * 
         * @param value
         *     allowed object is
         *     {@link RequestForQuotation.Request.Cores }
         *     
         */
        public void setCores(RequestForQuotation.Request.Cores value) {
            this.cores = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="TotalCores" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="Nodes">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="NodeCount" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                   &lt;element name="NodeCores" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "totalCores",
            "nodes"
        })
        public static class Cores {

            @XmlElement(name = "TotalCores")
            protected BigInteger totalCores;
            @XmlElement(name = "Nodes")
            protected RequestForQuotation.Request.Cores.Nodes nodes;

            /**
             * Gets the value of the totalCores property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTotalCores() {
                return totalCores;
            }

            /**
             * Sets the value of the totalCores property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTotalCores(BigInteger value) {
                this.totalCores = value;
            }

            /**
             * Gets the value of the nodes property.
             * 
             * @return
             *     possible object is
             *     {@link RequestForQuotation.Request.Cores.Nodes }
             *     
             */
            public RequestForQuotation.Request.Cores.Nodes getNodes() {
                return nodes;
            }

            /**
             * Sets the value of the nodes property.
             * 
             * @param value
             *     allowed object is
             *     {@link RequestForQuotation.Request.Cores.Nodes }
             *     
             */
            public void setNodes(RequestForQuotation.Request.Cores.Nodes value) {
                this.nodes = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="NodeCount" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *         &lt;element name="NodeCores" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "nodeCount",
                "nodeCores"
            })
            public static class Nodes {

                @XmlElement(name = "NodeCount", required = true)
                protected BigInteger nodeCount;
                @XmlElement(name = "NodeCores", required = true)
                protected BigInteger nodeCores;

                /**
                 * Gets the value of the nodeCount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getNodeCount() {
                    return nodeCount;
                }

                /**
                 * Sets the value of the nodeCount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setNodeCount(BigInteger value) {
                    this.nodeCount = value;
                }

                /**
                 * Gets the value of the nodeCores property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getNodeCores() {
                    return nodeCores;
                }

                /**
                 * Sets the value of the nodeCores property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setNodeCores(BigInteger value) {
                    this.nodeCores = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="TotalDiskSpace" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="NodeDiskSpace" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "totalDiskSpace",
            "nodeDiskSpace"
        })
        public static class Disk {

            @XmlElement(name = "TotalDiskSpace")
            protected BigInteger totalDiskSpace;
            @XmlElement(name = "NodeDiskSpace")
            protected BigInteger nodeDiskSpace;

            /**
             * Gets the value of the totalDiskSpace property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTotalDiskSpace() {
                return totalDiskSpace;
            }

            /**
             * Sets the value of the totalDiskSpace property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTotalDiskSpace(BigInteger value) {
                this.totalDiskSpace = value;
            }

            /**
             * Gets the value of the nodeDiskSpace property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNodeDiskSpace() {
                return nodeDiskSpace;
            }

            /**
             * Sets the value of the nodeDiskSpace property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNodeDiskSpace(BigInteger value) {
                this.nodeDiskSpace = value;
            }

        }

    }

}
